name = "Hack"
uuid = "122dce33-e0b6-4015-9cfe-1a0cf74415dc"
authors = ["Thomas Harris <thomasharris@math.arizona.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
